### ISSUE TITLE
My Skins Glitching

### ISSUE THREAD

**Issue by Pippsa** [MineLittlePony/Community-Skin-Pack#10]
![2023-03-23_04 58 45](https://user-images.githubusercontent.com/128669707/227107602-594db99c-91d5-4f73-85f9-2550fb2b6a43.png)
my skins glitching like this

**Comment by Sollace** [comment]
This isn't really the place to ask. This repository is for collecting skins made by the community. You can come join our discord server (linked from https://minelittlepony-mod.com/ ) if you need more specific help with this issue.
