### ISSUE TITLE
Button Mash Skin Submission

### ISSUE THREAD

**Issue by KarinaAE123** [MineLittlePony/Community-Skin-Pack#5]
I want to submit a skin of a 'fandom' pony, Button Mash. I made it using an outdated skin editor a while ago, but I think it fits in with this skinpack. This skin doesn't have the show accurate colors of the character because Jan Animation Studio's scheme was slightly different than how it appears in the show (season five onwards his coat/mane is redder). I am considering making a new rendition with the updated color scheme when I get the time.

![Button Mash](https://user-images.githubusercontent.com/32432795/68443199-dba67f00-0198-11ea-94a5-63156342bd45.png)

**Link to download texture:** (http://ponyskincraft.com/download.php?id=145031&name=Button%20Mash.png)

**Comment by Sollace** [comment]
@KarinaAE123 Thanks for the submission!

Can you please observe the design guidelines for skins already in the pack. (see Sweetie Belle's texture for reference).

Unfortunately we can't accept skins that haven't been cleaned up, or that use the old texture layout.

**Comment by KarinaAE123** [comment]
Thanks for responding! I just started learning how to skin so I'll look at what needs to be improved since I've gotten way better since the beginning. :)
