### ISSUE TITLE
Skins Submission (AT LAST)

### ISSUE THREAD

**Issue by KarinaAE123** [MineLittlePony/Community-Skin-Pack#6]
MONTHS AGO, I made several mlp skins that I was planning to submit to the official skinpack. I don't want to write-and you surely wouldn't want to read-a thirty-page essay, but I'll simply say that some scary and traumatic stuff went down in my personal life during the last months of 2019. Anyway, better late than never.

The PNG files will be listed in the order of my best to worst. (A long time ago I attempted to submit some skins that were only supported in the legacy format, but some of them have been updated to look better and display show accurate colors as required)

![moon_dancer](https://user-images.githubusercontent.com/32432795/77234059-97c97a80-6b79-11ea-83ee-5b4a30a5d464.png)
Moondancer is at the top because it's mostly a recolor of twilight, with the mane and tail, but is a simple character that quite of bit of people like so she was one of the first and complex skins I created.

![gabby](https://user-images.githubusercontent.com/32432795/77234112-fee72f00-6b79-11ea-91b4-896a07f095d3.png)
Gabby's skin. Fits in but the 'saddle bag' accessory may be removed if desired.

![starlight_glimmer](https://user-images.githubusercontent.com/32432795/77234191-774df000-6b7a-11ea-8d2d-17797cfa0102.png) Starlight Glimmer's skin. Basically another variant of the 'our town' Starlight, but obviously recolored and given her real cutiemark.

![button_mash](https://user-images.githubusercontent.com/32432795/77234293-2ee30200-6b7b-11ea-84db-7bf96b3afc0d.png)
Button Mash's skin. The color palette references JanAnimation's imagining of the character, the more recent in-show colors of Button Mash is different. This would be in the fandom category.

![bright_mac](https://user-images.githubusercontent.com/32432795/77234348-98fba700-6b7b-11ea-8eff-f2bf235a214d.png)
Bright Mac's skin. Utilizes the hat accessory (used Big Mac's skin as a base).

![apple_bloom (cutiemark)](https://user-images.githubusercontent.com/32432795/77234375-d2341700-6b7b-11ea-8493-548e5294c8e3.png)
An updated Applebloom skin that displays her cutiemark.

![queen_novo](https://user-images.githubusercontent.com/32432795/77234396-19baa300-6b7c-11ea-8d2c-ef82ca4309c9.png)
Queen Novo's skin. The queen of the hippogriffs in My Little Pony: The Movie; I'm pretty sure there isn't a skin for one of the movie exclusive characters yet, so here is one.

![daybreaker](https://user-images.githubusercontent.com/32432795/77234453-83d34800-6b7c-11ea-92ae-afcb489a1320.png)
Daybreaker's skin. I had to refer to deviantart vectors sampled from her episode since at the time mlpvectorclub didn't have her yet.

I hope most of these meet your standards, this mod was my childhood so I'm glad to contribute! :)

**Comment by Sollace** [comment]
These look pretty nice. How would you like yourself credited in the pack?

**Comment by KarinaAE123** [comment]
Just by my mc username: KarinaAE123. Nothing fancy. 🙂

**Comment by Sollace** [comment]
Okay! @KarinaAE123 I will convert this to a PR and merge it some time tomorrow (or this week). Give me a slap if I forget.:P

**Comment by KarinaAE123** [comment]
Alright fam! 👍
