### ISSUE TITLE
request!

### ISSUE THREAD

**Issue by lunarletters** [MineLittlePony/Community-Skin-Pack#9]
hi! i made an account for this lol, 
i wanted to suggest possibly adding a sunset shimmer minecraft skin! i also would like to offer more fandom selections, i have a toyhouse account and you'd be more than welcome to goof around and make skins of any of the characters on there for the fandom folder! i may or may not make some skins of my ocs as well,  [here is the link to my folder](https://toyhou.se/caitiheartz/characters/folder:3596951)

**Comment by Sollace** [comment]
Hi, Lunar! You'er perfectly welcome to make and submit any skins you want so long as they fit with the visual style and colour guides (if it's a canon character) of the skins already in the pack.

You can also join our discord. We have a channel there where people can make skin requests and show off their creations. https://minelittlepony-mod.com/

**Comment by MimzyFang** [comment]
closed for inactivity and because the original link is dead
